name: IridiumSkyblock
version: 2.1.9
description: Skyblock Redefined
main: com.iridium.iridiumskyblock.IridiumSkyblock
author: IridiumLLC
load: STARTUP
softdepend: [PlaceholderAPI, MVdWPlaceholderAPI, WildStacker, Vault, Multiverse-Core]
commands:
  island:
    aliases: ["is", "IridiumSkyblock"]
    description: Main plugin command