name: IridiumSkyblock
version: 2.1.0
description: Skyblock Redefined
main: com.peaches.epicskyblock.EpicSkyblock
author: [Peaches_MLG, Riches]
softdepend: [PlaceholderAPI]
commands:
  island:
    aliases: ["is", "EpicSkyblock"]
    description: Main plugin command