name: IridiumSkyblock
version: 2.1.4
description: Skyblock Redefined
main: com.iridium.iridiumskyblock.IridiumSkyblock
author: IridiumLLC
softdepend: [PlaceholderAPI, MVdWPlaceholderAPI, WildStacker]
api-version: 1.12.2
commands:
  island:
    aliases: ["is", "IridiumSkyblock"]
    description: Main plugin command