name: IridiumSkyblock
version: 2.1.0
description: Skyblock Redefined
main: com.iridium.iridiumskyblock.IridiumSkyblock
author: [Peaches_MLG, Riches]
softdepend: [PlaceholderAPI]
commands:
  island:
    aliases: ["is", "EpicSkyblock"]
    description: Main plugin command