name: IridiumSkyblock
version: 2.2.4
description: Skyblock Redefined
main: com.iridium.iridiumskyblock.IridiumSkyblock
author: IridiumLLC
softdepend: [PlaceholderAPI, MVdWPlaceholderAPI, WildStacker, Vault, Multiverse-Core, Essentials, EssentialsChat, ChatManager, DeluxeChat]
commands:
  island:
    aliases: ["is", "IridiumSkyblock"]
    description: Main plugin command