name: IridiumSkyblock
version: 2.1.3
description: Skyblock Redefined
main: com.iridium.iridiumskyblock.IridiumSkyblock
author: IridiumLLC
softdepend: [PlaceholderAPI]
commands:
  island:
    aliases: ["is", "IridiumSkyblock"]
    description: Main plugin command