name: IridiumSkyblock
version: 2.1.7
description: Skyblock Redefined
main: com.iridium.iridiumskyblock.IridiumSkyblock
author: IridiumLLC
softdepend: [PlaceholderAPI, MVdWPlaceholderAPI, WildStacker]
commands:
  island:
    aliases: ["is", "IridiumSkyblock"]
    description: Main plugin command