name: EpicSkyblock
version: 2.0.8
description: Skyblock Redefined
main: com.peaches.epicskyblock.EpicSkyblock
author: Peaches_MLG
softdepend: [PlaceholderAPI]
commands:
  island:
    aliases: ["is", "EpicSkyblock"]
    description: Main plugin command